name: Feature Request
description: Suggest anything here!
title: "💡 "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING A REQUEST
        
        Before opening a request, make sure a similar request doesn't already exist by [searching the existing requests](https://github.com/sam065819/computer/issues?q=is%3Aissue+label%3Aenhancement+).
        
        If a similar request already exists, **DO NOT reply** something like "i want this as well". Instead, react with :+1:. Only reply if you want to add additional info.

        Skip formalities like "hello" and do not use AI to "spice up" your request. keep it short and concise with only the information necessary
        ## One Request per issue

        Do not include multiple requests in one issue. If you are making 5 requests, make 5 separate issues

        Please make sure your request has common sense and that what you said is understandable.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: Explain the feature in detail
    validations:
      required: true

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      options:
        - label: I read the above and made sure my feature is possible and allowed
          required: false
        - label: "I checked the existing features of the bot and made sure it doesn't already have the feature I requested"
          required: false
        - label: "I [searched the existing requests](https://github.com/sam065819/computer/issues?q=is%3Aissue+label%3Aenhancement+) and made sure a similar request doesn't already exist"
          required: false
